### ISSUE TITLE
More Examples From Our Own Writing

### ISSUE THREAD

**Issue by maxveldink** [ryanbrookepayne/docsfordevs#2]
I really like the idea of getting real-time feedback on pieces that we're currently working on; it feels like the fastest way to put into practice what we're learning. Perhaps, given enough time, we could send out one persons work a few days before the next meeting, and have an in-person discussion around feedback, good and improvement spots, passing that through the lens of what we're learning.

**Comment by maxveldink** [comment]
@ryanbrookepayne Looks like I don't have access to add labels to Issues on this repo

**Comment by ryanbrookepayne** [comment]
@maxveldink Love it man! I will add that as part of the class structure.

**Comment by ryanbrookepayne** [comment]
@maxveldink We'll use your guide as an example in today's class.
